

-- 1. 🗺️ INSTA_TBL_LOCATION (지역 정보)

CREATE TABLE INSTA_TBL_LOCATION (
    LOCATION_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '지역 고유 ID',
    SIDO VARCHAR(50) NOT NULL COMMENT '시/도 (예: 서울특별시)',
    SIGUNGU VARCHAR(50) NOT NULL COMMENT '시/구/군 (예: 강남구)',
    FULL_NAME VARCHAR(100) NOT NULL UNIQUE COMMENT '전체 이름'
);


-- 2. 🏷️ INSTA_TBL_CATEGORY (카테고리/취미 주제) 
CREATE TABLE INSTA_TBL_CATEGORY (
    CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '카테고리 고유 ID',
    NAME VARCHAR(50) NOT NULL UNIQUE COMMENT '카테고리 이름 (예: 러닝, 독서 모임)',
    TYPE VARCHAR(10) NOT NULL COMMENT '주제 분류 (예: HOBBY, MEETING, FOOD)'
);


-- 3. 🧑‍🤝‍🧑 INSTA_TBL_USER (사용자)
CREATE TABLE INSTA_TBL_USER (
    USER_ID VARCHAR(300) PRIMARY KEY COMMENT '사용자 ID (소셜 로그인 대비 300자)',
    PASSWORD VARCHAR(255) NOT NULL COMMENT '비밀번호 (해시값)',
    USERNAME VARCHAR(100) NOT NULL COMMENT '사용자 이름 (표시 이름)',
    EMAIL VARCHAR(255) NOT NULL UNIQUE COMMENT '이메일',
    REGION_ID INT COMMENT '거주 지역 ID',
    HOBBIES JSON COMMENT '관심 취미 목록 (JSON 배열)',
    PROFILE_IMG VARCHAR(255) COMMENT '프로필 사진 URL',
    INTRO TEXT COMMENT '자기소개',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    FOREIGN KEY (REGION_ID) REFERENCES INSTA_TBL_LOCATION(LOCATION_ID)
);



-- 4. 📝 INSTA_TBL_FEED (게시물)
CREATE TABLE INSTA_TBL_FEED (
    FEED_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '게시물 고유 ID',
    USER_ID VARCHAR(300) NOT NULL COMMENT '작성자 ID',
    TITLE VARCHAR(255) COMMENT '게시물 제목',
    CONTENT TEXT NOT NULL COMMENT '게시물 본문',
    CATEGORY_ID INT COMMENT '주제/취미 카테고리 ID',
    LOCATION_ID INT COMMENT '게시물 작성 지역 ID',
    LATITUDE DECIMAL(10, 8) COMMENT '촬영 위치 위도',
    LONGITUDE DECIMAL(11, 8) COMMENT '촬영 위치 경도',
    LIKE_COUNT INT DEFAULT 0 COMMENT '좋아요 수 (캐싱용)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    FOREIGN KEY (USER_ID) REFERENCES INSTA_TBL_USER(USER_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES INSTA_TBL_CATEGORY(CATEGORY_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES INSTA_TBL_LOCATION(LOCATION_ID)
);






-- 5. 🖼️ INSTA_TBL_MEDIA (이미지/영상)
CREATE TABLE INSTA_TBL_MEDIA (
    MEDIA_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '미디어 고유 ID',
    FEED_ID INT NOT NULL COMMENT '게시물 ID',
    MEDIA_URL VARCHAR(255) NOT NULL COMMENT '미디어 파일 URL',
    MEDIA_TYPE VARCHAR(10) NOT NULL COMMENT 'IMAGE 또는 VIDEO',
    ORDER_NUM INT COMMENT '여러 파일일 경우 순서',
    FOREIGN KEY (FEED_ID) REFERENCES INSTA_TBL_FEED(FEED_ID)
);






-- 6. 소셜 기능 테이블 조아요
CREATE TABLE INSTA_TBL_LIKE (
    FEED_ID INT NOT NULL COMMENT '게시물 ID',
    USER_ID VARCHAR(300) NOT NULL COMMENT '좋아요 누른 사용자 ID',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FEED_ID, USER_ID),
    FOREIGN KEY (FEED_ID) REFERENCES INSTA_TBL_FEED(FEED_ID),
    FOREIGN KEY (USER_ID) REFERENCES INSTA_TBL_USER(USER_ID)
);







-- 7. 소셜 기능 테이블 댓글
CREATE TABLE INSTA_TBL_COMMENT (
    COMMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FEED_ID INT NOT NULL,
    USER_ID VARCHAR(300) NOT NULL,
    CONTENT TEXT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FEED_ID) REFERENCES INSTA_TBL_FEED(FEED_ID),
    FOREIGN KEY (USER_ID) REFERENCES INSTA_TBL_USER(USER_ID)
);




-- 8. 소셜 기능 테이블 팔로우
CREATE TABLE INSTA_TBL_FOLLOW (
    FOLLOWER_ID VARCHAR(300) NOT NULL COMMENT '팔로우하는 사람',
    FOLLOWING_ID VARCHAR(300) NOT NULL COMMENT '팔로우 당하는 사람',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (FOLLOWER_ID, FOLLOWING_ID),
    FOREIGN KEY (FOLLOWER_ID) REFERENCES INSTA_TBL_USER(USER_ID),
    FOREIGN KEY (FOLLOWING_ID) REFERENCES INSTA_TBL_USER(USER_ID)
);



-- 9. 🗨️ INSTA_TBL_CHAT_ROOM (채팅방 관리)
-- 두 사용자 간의 대화방 자체를 정의합니다.

CREATE TABLE INSTA_TBL_CHAT_ROOM (
    ROOM_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '채팅방 고유 ID',
    USER1_ID VARCHAR(300) NOT NULL COMMENT '사용자 ID 1',
    USER2_ID VARCHAR(300) NOT NULL COMMENT '사용자 ID 2',
    LAST_MESSAGE_ID INT COMMENT '마지막 메시지 ID (캐싱용)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    
    -- 두 사용자 ID 쌍이 중복되지 않도록 UNIQUE 인덱스 설정
    -- (USER1_ID, USER2_ID) 순서와 (USER2_ID, USER1_ID) 순서를 모두 고려해야 하나,
    -- 일단 빠른 개발을 위해 ID 순서대로 저장하도록 규칙을 정하고 아래와 같이 설정
    UNIQUE KEY unique_room (USER1_ID, USER2_ID), 
    
    FOREIGN KEY (USER1_ID) REFERENCES INSTA_TBL_USER(USER_ID),
    FOREIGN KEY (USER2_ID) REFERENCES INSTA_TBL_USER(USER_ID)
);


-- 10. ✉️ INSTA_TBL_CHAT_MESSAGE (채팅 메시지)
-- 채팅방에서 주고받는 메시지 내용을 저장합니다.

CREATE TABLE INSTA_TBL_CHAT_MESSAGE (
    MESSAGE_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '메시지 고유 ID',
    ROOM_ID INT NOT NULL COMMENT '채팅방 ID',
    SENDER_ID VARCHAR(300) NOT NULL COMMENT '발신자 ID',
    CONTENT TEXT COMMENT '메시지 내용 (텍스트)',
    MEDIA_URL VARCHAR(255) COMMENT '미디어 파일 URL (사진, 영상 등)',
    MESSAGE_TYPE VARCHAR(10) NOT NULL DEFAULT 'TEXT' COMMENT '메시지 타입 (TEXT, IMAGE, VIDEO)',
    IS_READ TINYINT(1) DEFAULT 0 COMMENT '수신자가 읽었는지 여부 (0: 안 읽음, 1: 읽음)',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '전송 일시',    
    FOREIGN KEY (ROOM_ID) REFERENCES INSTA_TBL_CHAT_ROOM(ROOM_ID),
    FOREIGN KEY (SENDER_ID) REFERENCES INSTA_TBL_USER(USER_ID)
);



-- 11. 🏷️ INSTA_TBL_HASHTAG (해시태그 정보 - 탐색/검색 기능)
-- 사용된 해시태그 자체를 관리하여 검색 기능의 기반을 마련합니다.

CREATE TABLE INSTA_TBL_HASHTAG (
    HASHTAG_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '해시태그 고유 ID',
    TAG_NAME VARCHAR(100) NOT NULL UNIQUE COMMENT '해시태그 이름 (예: 강남맛집)',
    POST_COUNT INT DEFAULT 0 COMMENT '해당 태그를 사용한 게시물 수 (캐싱용)'
);


-- 12. 🔗 INSTA_TBL_FEED_HASHTAG (게시물-해시태그 연결 - 탐색/검색 기능)
-- 게시물과 해시태그 간의 다대다(N:M) 관계를 연결하는 테이블입니다.
CREATE TABLE INSTA_TBL_FEED_HASHTAG (
    FEED_ID INT NOT NULL COMMENT '게시물 ID',
    HASHTAG_ID INT NOT NULL COMMENT '해시태그 ID',
    
    PRIMARY KEY (FEED_ID, HASHTAG_ID),
    
    FOREIGN KEY (FEED_ID) REFERENCES INSTA_TBL_FEED(FEED_ID),
    FOREIGN KEY (HASHTAG_ID) REFERENCES INSTA_TBL_HASHTAG(HASHTAG_ID)
);

-- 13. ❤️ INSTA_TBL_NOTIFICATION (알림/활동)
-- 좋아요, 댓글, 팔로우 등 사용자의 활동 기록을 저장하여 알림 기능을 확장할 때 사용합니다.

CREATE TABLE INSTA_TBL_NOTIFICATION (
    NOTI_ID INT PRIMARY KEY AUTO_INCREMENT COMMENT '알림 고유 ID',
    RECEIVER_ID VARCHAR(300) NOT NULL COMMENT '알림을 받는 사용자 ID',
    SENDER_ID VARCHAR(300) NOT NULL COMMENT '알림을 발생시킨 사용자 ID',
    NOTI_TYPE VARCHAR(20) NOT NULL COMMENT '알림 타입 (LIKE, COMMENT, FOLLOW 등)',
    TARGET_ID INT COMMENT '알림 대상 (Feed ID, Comment ID 등 - Nullable)',
    IS_READ TINYINT(1) DEFAULT 0 COMMENT '읽음 여부',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '생성 일시',
    
    FOREIGN KEY (RECEIVER_ID) REFERENCES INSTA_TBL_USER(USER_ID),
    FOREIGN KEY (SENDER_ID) REFERENCES INSTA_TBL_USER(USER_ID)
);


-- 💡 최종 테이블 구조 (총 13개)
-- 최종 테이블 구조 (총 13개)이제 DM, 알림, 탐색 기능 확장을 위한 5개 테이블을 포함하여 총 13개의 테이블 구조가 완성되었습니다.
-- 번호테이블명기능1~8(기존 핵심 기능 테이블)사용자, 피드, 좋아요, 댓글, 팔로우, 지역, 카테고리, 미디어
-- 9INSTA_TBL_CHAT_ROOMDM 기능: 채팅방 관리
-- 10INSTA_TBL_CHAT_MESSAGEDM 기능: 메시지 내용 저장
-- 11INSTA_TBL_HASHTAG탐색/검색 기능: 해시태그 정의
-- 12INSTA_TBL_FEED_HASHTAG탐색/검색 기능: 게시물-해시태그 연결
-- 13INSTA_TBL_NOTIFICATION알림 기능: 사용자 활동 기록

